spring:
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: mysql://ec2-18-220-138-199.us-east-2.compute.amazonaws.com:3306/nft
    username: user
    password: User123!
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://ec2-18-220-138-199.us-east-2.compute.amazonaws.com:3306/nft
      username: user
      password: User123!
      driver-class-name: com.mysql.jdbc.Driver

cloud:
  aws:
    credentials:
      accessKey: AKIA23475HTAJPJGTN3T
      secretKey: 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
    s3:
      bucket: sejong-nft-bucket
    region:
      static: us-east-2
    stack:
      auto: false
